set(_CATKIN_CURRENT_PACKAGE "turtlebot3_move")
set(turtlebot3_move_VERSION "0.0.0")
set(turtlebot3_move_MAINTAINER "thomas <thomas@todo.todo>")
set(turtlebot3_move_PACKAGE_FORMAT "2")
set(turtlebot3_move_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(turtlebot3_move_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(turtlebot3_move_BUILDTOOL_DEPENDS "catkin")
set(turtlebot3_move_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot3_move_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(turtlebot3_move_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(turtlebot3_move_TEST_DEPENDS )
set(turtlebot3_move_DOC_DEPENDS )
set(turtlebot3_move_URL_WEBSITE "")
set(turtlebot3_move_URL_BUGTRACKER "")
set(turtlebot3_move_URL_REPOSITORY "")
set(turtlebot3_move_DEPRECATED "")